### ISSUE TITLE
The Medical Language Model  has been added to the gallery at awesome-streamlit.org. Hope it's ok?

### ISSUE THREAD

**Issue by MarcSkovMadsen** [gtancev/MLML#1]
Hi Georgi

I've added your awesome Medical Language Model to the gallery at awesome-streamlit.org

Your app and article is some of the best out there on Streamlit so far. Congratulations.

I've also refactored it a bit. 1) To make it work with the gallery 2) Some smaller changes due to my personal preferences :-)

Hope it's ok?

Feel free to improve via a pull request at https://github.com/marcskovmadsen/awesome-streamlit

Marc

![image](https://user-images.githubusercontent.com/42288570/68067171-73dcd800-fd43-11e9-8b4f-bf6e37f5c881.png)

**Comment by MarcSkovMadsen** [comment]
And if you like to promote things on social media feel free to do so. The awesome-streamlit.org site and gallery could be mentioned as well. It needs a little bit of marketing. :-)

Thanks.

**Comment by gtancev** [comment]
Hi Marc. I'm fine with this. Thanks!
